# Generated by Django 5.0.3 on 2024-03-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='home/healthprofessionals/'),
        ),
    ]
