# Generated by Django 5.0.3 on 2024-03-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_car_car_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_picture',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
