# Generated by Django 5.0.3 on 2024-03-28 22:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_driver_driver_picture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_travel', models.DateField(blank=True, null=True)),
                ('expected_return_date', models.DateTimeField(blank=True, null=True)),
                ('destination', models.CharField(blank=True, max_length=100)),
                ('number_of_passengers', models.IntegerField()),
                ('purpose_of_travel', models.CharField(blank=True, max_length=100)),
                ('requestor_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(verbose_name=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.driver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
