# Generated by Django 5.0.3 on 2024-03-28 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_approvedreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvedreservation',
            name='appointment_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvedreservation',
            name='contact_number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvedreservation',
            name='office_department_college',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvedreservation',
            name='requestor_address',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
