# Generated by Django 5.0.3 on 2024-03-29 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_approvedreservation_appointment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedreservation',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
