# Generated by Django 5.0.3 on 2024-03-29 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_approvedreservation_expected_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvedreservation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
