# Generated by Django 5.0.3 on 2024-03-29 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_approvedreservation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedreservation',
            name='is_active',
        ),
    ]
