# Generated by Django 5.0.3 on 2024-03-29 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_remove_approvedreservation_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedreservation',
            name='user',
        ),
    ]
