# Generated by Django 5.0.3 on 2024-03-30 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_remove_approvedreservation_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
